import { getDb } from "../client";

/**
 * Reads/writes against the runs table (SPEC.md section 5). The id is
 * generated by the caller (src/lib/runs) rather than left to the column
 * default, so a RunHandle's runId is available synchronously, before the
 * INSERT completes.
 */
export async function createRun(params: { id: string; mode: string; pack: string; model: string }): Promise<string> {
  const sql = getDb();
  await sql`
    INSERT INTO runs (id, mode, pack, model) VALUES (${params.id}, ${params.mode}, ${params.pack}, ${params.model})
  `;
  return params.id;
}

export async function finishRun(runId: string, summary: string | null, stats: Record<string, unknown>): Promise<void> {
  const sql = getDb();
  const status = "error" in stats ? "failed" : "completed";
  await sql`
    UPDATE runs SET finished_at = now(), status = ${status}, summary = ${summary}, stats = ${sql.json(JSON.parse(JSON.stringify(stats)))}
    WHERE id = ${runId}
  `;
}
